---
- name: Upgrade Operating System
  apt:
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    upgrade: full
  register: os_upgrade_info

- name: Restart Node If Operating System Upgraded
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  when: os_upgrade_info.changed

- name: Wait For Node to Be Ready
  wait_for:
    port: 22
    timeout: 15
    connect_timeout: 3
    delay: 5
    state: present
  when: os_upgrade_info.changed

- name: Install Required Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - rsync
